source 'https://rubygems.org'

# for enabling or disabling features 
gem 'flipper'
gem 'flipper-active_record'

group :development do
  gem 'foreman'
  gem 'brakeman', require: false
  
  # Better errors handler
  gem 'better_errors'
  gem 'binding_of_caller'
  
  # thin instead webrick
  gem 'thin'
end

group :development, :test do
  # for N+1
  gem 'bullet'

  # for debug
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  
  # for application preloader
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-commands-spinach'

  # for lint
  gem 'rubocop', '~> 0.47.1', require: false
  gem 'rubocop-rspec', '~> 1.15.0', require: false
end
